import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.scss";
import "react-perfect-scrollbar/dist/css/styles.css";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "./(protected)/_components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
    searchParams?: { [key: string]: string | string[] | undefined };
}) {
    const session = await auth();

    return (
        <SessionProvider session={session}>
            <html lang="en">
                <body className={inter.className}>
                    <Toaster />
                    <div
                        style={{
                            backgroundColor: "#121217",
                            minHeight: "100vh",
                        }}
                        className=" w-full flex flex-col gap-y-5">
                        <Navbar key={"1"} />
                        <div
                            className="w-full flex "
                            style={{ minHeight: "calc(80vh - 2.5rem)" }}>
                            {children}
                        </div>
                    </div>
                </body>
            </html>
        </SessionProvider>
    );
}
